sr: 22050 # Sample rate.
n_fft: 1024 # fft points (samples)
frame_shift: 0.0125 # seconds
frame_length: 0.05 # seconds
n_mels: 80 # Number of Mel banks to generate
power: 1.2 # Exponent for amplifying the predicted magnitude
n_iter: 60 # Number of inversion iterations
preemphasis: .97 # or None
max_db: 100
ref_db: 20
top_db: 15